## Test PHPStan analysis in GitHub Actions
name: PHPStan Analysis
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
# Section "on" : définit les événements qui déclenchent le workflow.
# Ici, le workflow s'exécute lors des pushs et des pull requests sur la branche "main".

jobs:
  phpstan:
    runs-on: ubuntu-latest
    # Définition d'un job nommé "phpstan" qui s'exécute sur la dernière version d'Ubuntu disponible.
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Récupère le code source du dépôt pour que les étapes suivantes puissent y accéder.
      # On utilise l'action officielle "actions/checkout" pour cloner le dépôt.

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring
      # Configure l'environnement PHP avec la version 8.3.
      # On installe aussi l'extension, pour gérer les string non-ASCII.

      - name: Install dependencies
        run: composer install  --no-progress --no-suggest --prefer-dist
      # Installe les dépendances du projet via Composer.
      # On accélère l'installation avec l'option --prefer-dist
      # On évite les messages inutiles avec --no-progress et --no-suggest.

      - name: Run PHPStan
        run: composer run stan-check
      # Exécute PHPStan pour analyser le code à la recherche d'erreurs (mauvais typages...) pour compléter les tests unitaires.
      # Si des erreurs sont détectées, le job renvoie un statut “failed” et le workflow s’arrête.